#!/usr/bin/env bash
#prints Best school, bad and good luck
var=1
while [ $var -le 20 ]
do
	if [ $var -eq 4 ]
	then
		echo $var
		echo "bad luck from China"
	elif [ $var -eq 9 ]
	then
		echo $var
		echo "good luck from Japan"
	elif [ $var -eq 17 ]
	then
		echo $var
		echo "bad luck from Italy"
	else
		echo $var
	fi
	var=$(( var + 1 ))
done
