#!/usr/bin/env bash
# a Bash script that gives you information about the school file.
file="school"
if [ -e "$file" ]
then
	echo "$file file exists"
	if [ -n $file ]
	then
		echo "$file file is empty"
	elif [ -z "$file" ] 
	then
		echo "$file file is not empty"
	elif [ -f "school" ]
	then
		echo "hello"
	fi
else
	echo "$file file does not exist"
fi
